<?php

namespace AdminBundle\Repository;

/**
 * EstudianteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudianteRepository extends \Doctrine\ORM\EntityRepository{
  // Todos los estudiantes ordenados por nombre
  public function findAllOrderedByNombre(){
		$query=$this->getEntityManager()->createQuery(
      'SELECT e
			 FROM AdminBundle:Estudiante e
			 ORDER BY e.nombre ASC');
		return $query->getResult();
	}
   // Todos los estudiantes mayores de edad
	public function findAllMayores(){
		$query=$this->getEntityManager()->createQuery(
            'SELECT e
             FROM AdminBundle:Estudiante e
             WHERE e.edad >= :valor
             ORDER BY e.edad ASC')
            ->setParameter('valor', 18);
		return $query->getResult();
	}
  // Todos los estudiantes menores de edad
	public function findAllMenores(){
		$query=$this->createQueryBuilder('e')
            ->where('e.edad < :valor')
            ->setParameter('valor', 18)
            ->orderBy('e.edad', 'DESC')
            ->getQuery();
		return $query->getResult();
	}
  // Recuperar los estudiantes y sus cursos
	public function findEstudiantesCurso(){
	    $query = $this->getEntityManager()
	        ->createQuery(
	            'SELECT e, c
              FROM AdminBundle:Estudiante e
	            JOIN e.curso c');
	    try {
	        return $query->getResult();
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}
  // Recuperar cursos y sus estudiantes
	public function findCursosEstudiantes(){
	    $query = $this->getEntityManager()
	        ->createQuery(
	            'SELECT c, e
	             FROM AdminBundle:Curso c
	             JOIN c.estudiantes e');
	    try {
	        return $query->getResult();
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}
}
